const http = require('node:http');
const fs = require('node:fs');
const path = require('node:path');
const crypto = require('node:crypto');
const { URL } = require('node:url');

const PORT = Number(process.env.PORT || 3000);
const HOST = process.env.HOST || '127.0.0.1';
const PUBLIC = path.join(__dirname, 'public');

const rows = [
  ['checkout-api','Checkout API','Payments','sha1:7f31c9a','production','enforce','tier-1','Payment safety gate','Block risky payment changes; warn when operational confidence is incomplete.',[
    ['tests','CI','Test reliability','ratio',98.6,98,'higher','%','Pass rate adjusted for flaky retries',25,'test'],['cve','Trivy','Critical vulnerabilities','count',0,0,'lower','critical','Critical CVEs introduced by this change',30,'security'],['latency','APM','Checkout p95 latency','delta',282,300,'lower','ms','Canary p95 vs 7-day production baseline',20,'performance'],['errors','Canary','Error budget burn','threshold',1.1,2,'lower','x','One-hour burn rate normalized to SLO',15,'production_slo'],['review','Git','Required approvals','ratio',100,100,'higher','%','Signed approvals / required approvals',10,'governance']]],
  ['identity-service','Identity Service','Platform Security','sha1:21d48e0','staging','warn','tier-1','Authentication integrity','Require security evidence and protect login success and latency.',[
    ['contract','Pact','Contract tests','ratio',100,100,'higher','%','Passed consumer contracts / total contracts',20,'contract'],['secrets','gitleaks','Leaked secrets','count',0,0,'lower','findings','Verified secrets introduced in diff',30,'security'],['login','Synthetic','Login success','ratio',99.7,99.5,'higher','%','Successful regional login journeys',20,'test'],['latency','APM','Token issue p99','delta',410,450,'lower','ms','P99 token issuance during canary',15,'performance'],['threat','Review','Threat model freshness','threshold',24,90,'lower','days','Days since relevant threat model review',15,'governance']]],
  ['catalog-web','Catalog Web','Storefront','sha1:a918be2','preview','observe','tier-2','Customer experience','Balance functional, accessibility, performance, and visual confidence.',[
    ['e2e','Playwright','Critical journeys','ratio',97,98,'higher','%','Stable pass rate for revenue journeys',25,'test'],['a11y','Axe','Accessibility violations','count',1,0,'lower','serious','Serious or critical WCAG violations',20,'static_analysis'],['lcp','Lighthouse','Largest Contentful Paint','threshold',2.3,2.5,'lower','s','Mobile p75 LCP on preview build',20,'performance'],['visual','Percy','Visual diff','delta',0.7,1,'lower','%','Changed pixels excluding approved regions',15,'test'],['bundle','Build','JS bundle growth','delta',2.1,3,'lower','%','Compressed entry bundle delta',20,'performance']]],
  ['recommendation-engine','Recommendation Engine','Personalization','sha1:55c029f','shadow','warn','tier-2','Responsible model promotion','Promote only when quality improves without fairness or stability regressions.',[
    ['ndcg','ML Eval','Ranking quality NDCG','distribution',0.812,0.8,'higher','','Offline NDCG@10 on holdout set',25,'model_eval'],['drift','Feature Store','Feature drift PSI','distribution',0.11,0.2,'lower','','Max population stability index',20,'model_eval'],['fairness','ML Eval','Exposure disparity','distribution',3.4,5,'lower','%','Maximum segment exposure gap',25,'model_eval'],['inference','Shadow','Inference p95','delta',74,80,'lower','ms','Shadow traffic p95 model latency',15,'performance'],['coverage','Data Quality','Feature completeness','ratio',99.2,99,'higher','%','Non-null required online features',15,'data_quality']]],
  ['fulfillment-worker','Fulfillment Worker','Operations','sha1:c87e41d','canary','enforce','tier-1','Operational resilience','Protect order processing, recovery, observability, and safe rollout.',[
    ['integration','CI','Integration tests','ratio',99,98,'higher','%','Pass rate across carrier integrations',20,'test'],['lag','Kafka','Consumer lag','threshold',640,1000,'lower','messages','Max canary partition lag over 15 min',20,'performance'],['dlq','Runtime','Dead-letter rate','ratio',0.03,0.1,'lower','%','Dead-lettered / processed messages',25,'production_slo'],['rollback','Deploy','Rollback readiness','verdict',100,100,'higher','%','Validated rollback steps completed',20,'deploy_verification'],['alerts','Observability','Runbook coverage','ratio',92,90,'higher','%','Actionable alerts linked to current runbooks',15,'governance']]]
];

const applications = rows.map(([id,name,owner,change,environment,mode,tier,title,description,signals]) => ({ id,name,owner,change,environment,mode,tier,policy:{title,description},signals:signals.map(([sid,source,label,kind,raw,target,direction,unit,transform,weight,category])=>({id:sid,source,label,kind,raw,target,direction,unit,transform,weight,category,failClosed:category==='security'})) }));
const runtime = new Map(applications.map(app => [app.id,{mode:app.mode,overrides:{},statuses:{},trust:{},waivers:{},thresholds:{},history:[],revision:0}]));
const nowIso=()=>new Date().toISOString();
const uid=prefix=>`${prefix}-${Date.now().toString(36)}-${crypto.randomBytes(2).toString('hex')}`;

function normalize(signal,raw=signal.raw,target=signal.target){if(target===0)return raw===0?100:Math.max(0,100-raw*35);const ratio=signal.direction==='higher'?raw/target:target/Math.max(raw,.0001);return Math.round(Math.max(0,Math.min(1,ratio))*100);}
function makeSubjects(app){const short=app.change.replace('sha1:','');const hash=s=>crypto.createHash('sha256').update(`${short}-${s}`).digest('hex').slice(0,12);return [{kind:'commit',label:'Source change',digest:app.change,stage:'commit'},{kind:'build',label:'CI execution',digest:`sha256:${hash('build')}`,stage:'build'},{kind:'artifact',label:'Immutable image',digest:`sha256:${hash('artifact')}`,stage:'integration'},{kind:'deployment',label:`${app.environment} instance`,digest:`sha256:${hash(app.environment)}`,stage:'deployment'},{kind:'service_window',label:'Production window',digest:`window:${short}-15m`,stage:'production'}];}

function ruleForSignal(s){
  if(s.status==='pending')return{rule:`evidence.${s.id}.complete`,verdict:'unknown',class:'blocking',cause:'required_evidence_pending',detail:`${s.label} is still running; deadline ${s.deadline}.`,remediation:{action:'await_or_request_exception'},evidence:[s.signalId]};
  if(['expired','missing'].includes(s.status))return{rule:`evidence.${s.id}.complete`,verdict:'unknown',class:'blocking',cause:s.status==='expired'?'evidence_expired':'required_evidence_missing',detail:`${s.label} is ${s.status}.`,remediation:{action:'rerun_check'},evidence:[]};
  if(s.status==='outage')return{rule:`evidence.${s.id}.available`,verdict:s.failClosed?'fail':'unknown',class:s.failClosed?'blocking':'advisory',cause:'producer_unavailable',detail:`${s.source} is unavailable; ${s.failClosed?'this category fails closed':'using degraded mode'}.`,remediation:{action:'check_producer_status'},evidence:[]};
  if(s.waiver)return{rule:`${s.category}.${s.id}`,verdict:'warn',class:'advisory',cause:'temporary_waiver',detail:`Finding waived by ${s.waiver.owner} until ${s.waiver.expiresAt}.`,remediation:{action:'review_waiver',ticket:s.waiver.ticket},evidence:[s.signalId]};
  if(!s.passed&&s.trust==='quarantined')return{rule:`${s.category}.${s.id}`,verdict:'warn',class:'advisory',cause:'check_quarantined',detail:`${s.label} failed but lost its veto after conflicting results.`,remediation:{action:'fix_or_restore_check'},evidence:[s.signalId]};
  if(!s.passed)return{rule:`${s.category}.${s.id}`,verdict:'fail',class:s.weight>=25?'blocking':'advisory',cause:'threshold_exceeded',detail:`Measured ${s.raw}${s.unit?` ${s.unit}`:''}; required ${s.direction==='higher'?'>=':'<='} ${s.target}${s.unit?` ${s.unit}`:''}.`,remediation:{action:'open_source_run',url:`https://example.invalid/runs/${s.signalId}`},evidence:[s.signalId]};
  return{rule:`${s.category}.${s.id}`,verdict:'pass',class:s.weight>=25?'blocking':'advisory',detail:`${s.label} satisfies its requirement.`,evidence:[s.signalId]};
}

function evaluate(app,options={}){
  const state=runtime.get(app.id),subjects=makeSubjects(app),observedAt=nowIso();
  const signals=app.signals.map((base,index)=>{const target=Number(state.thresholds[base.id]?.applied??base.target),raw=Number(state.overrides[base.id]??base.raw),statusInfo=state.statuses[base.id]||{status:'present'},passed=base.direction==='higher'?raw>=target:raw<=target,trust=state.trust[base.id]||'active';return{...base,target,raw,score:normalize(base,raw,target),passed,trust,gating:trust==='active',status:statusInfo.status,deadline:statusInfo.deadline,waiver:state.waivers[base.id]||null,signalId:`sig-${app.id}-${base.id}`,subject:subjects[Math.min(index,subjects.length-1)].digest,occurredAt:observedAt,receivedAt:observedAt};});
  const rules=signals.map(ruleForSignal);const completeness={requiredPresent:signals.filter(s=>s.status==='present').map(s=>s.id),requiredMissing:signals.filter(s=>s.status==='missing').map(s=>s.id),pending:signals.filter(s=>s.status==='pending').map(s=>({checkId:s.id,deadline:s.deadline})),expired:signals.filter(s=>s.status==='expired').map(s=>s.id),missingDueToOutage:signals.filter(s=>s.status==='outage').map(s=>s.id)};
  const blockingFail=rules.some(r=>r.class==='blocking'&&r.verdict==='fail'),insufficient=completeness.requiredMissing.length||completeness.expired.length,pending=completeness.pending.length,advisory=rules.some(r=>r.class==='advisory'&&r.verdict!=='pass');
  let rawOutcome=blockingFail?'blocked':insufficient?'insufficient_evidence':pending?'require_additional_validation':advisory?'proceed_with_warning':'proceed',outcome=rawOutcome,modeDowngraded=false;
  if(state.mode==='observe'&&rawOutcome!=='proceed'){outcome='proceed';modeDowngraded=true;}if(state.mode==='warn'&&['blocked','insufficient_evidence'].includes(rawOutcome)){outcome='proceed_with_warning';modeDowngraded=true;}
  const confidence=Math.round(signals.reduce((n,s)=>n+s.score*s.weight,0)/signals.reduce((n,s)=>n+s.weight,0)),degraded=completeness.missingDueToOutage.length>0||rules.some(r=>r.cause==='check_quarantined'),decisionId=options.decisionId||`decision-${app.id}-${state.revision}`;
  return{...app,mode:state.mode,subjects,signals,rules,completeness,confidence,outcome,rawOutcome,modeDowngraded,degraded,decisionId,evidenceId:`evidence-${app.id}-${state.revision}`,policyDigest:`sha256:${crypto.createHash('sha256').update(`${app.id}-${state.mode}-${JSON.stringify(state.thresholds)}`).digest('hex').slice(0,16)}`,evaluatedAt:observedAt,thresholds:state.thresholds,history:state.history};
}

function recordDecision(app,cause){const state=runtime.get(app.id);state.revision+=1;const decision=evaluate(app,{decisionId:uid('decision')}),previous=state.history.at(-1),entry={decisionId:decision.decisionId,at:decision.evaluatedAt,outcome:decision.outcome,rawOutcome:decision.rawOutcome,cause,supersedes:previous?.decisionId||null,supersededBy:null};if(previous)previous.supersededBy=entry.decisionId;state.history.push(entry);return evaluate(app,{decisionId:entry.decisionId});}
function resetMemory(){for(const app of applications){Object.assign(runtime.get(app.id),{mode:app.mode,overrides:{},statuses:{},trust:{},waivers:{},thresholds:{},history:[],revision:0});recordDecision(app,'memory_reset');}return applications.map(evaluate);}
function applyAction(app,body){const state=runtime.get(app.id),signal=app.signals.find(s=>s.id===body.signalId)||app.signals[0];switch(body.action){
  case'degrade':state.overrides[signal.id]=signal.direction==='higher'?signal.target*.65:Math.max(signal.target*2,1);break;
  case'restore':state.overrides={};state.statuses={};state.trust={};state.waivers={};break;
  case'pending':state.statuses[signal.id]={status:'pending',deadline:new Date(Date.now()+4*3600e3).toISOString()};break;
  case'arrive':state.statuses[signal.id]={status:'present'};delete state.overrides[signal.id];break;
  case'outage':state.statuses[signal.id]={status:'outage'};break;
  case'flaky':state.trust[signal.id]='quarantined';state.overrides[signal.id]=signal.direction==='higher'?signal.target*.7:Math.max(signal.target*2,1);break;
  case'setMode':if(!['observe','warn','enforce'].includes(body.mode))throw Error('Invalid mode');state.mode=body.mode;break;
  case'threshold':{const requested=Number(body.value);if(!Number.isFinite(requested))throw Error('Invalid threshold');const floor=signal.direction==='higher'?signal.target*.75:signal.target===0?0:signal.target*1.5,applied=signal.direction==='higher'?Math.max(requested,floor):Math.min(requested,floor);state.thresholds[signal.id]={requested,applied,floor,clamped:requested!==applied,direction:signal.direction};break;}
  case'waive':state.waivers[signal.id]={justification:body.justification||'vulnerable_code_not_in_execute_path',owner:body.owner||app.owner,ticket:body.ticket||'CQP-POC',expiresAt:new Date(Date.now()+14*86400e3).toISOString()};break;
  case'regression':{const candidate=app.signals.find(s=>s.category==='production_slo')||app.signals.find(s=>s.category==='performance')||signal;state.overrides[candidate.id]=candidate.direction==='higher'?candidate.target*.5:Math.max(candidate.target*3,1);break;}
  default:throw Error('Unknown action');}return recordDecision(app,body.action);}
function attestation(app){const d=evaluate(app),statement={_type:'https://in-toto.io/Statement/v1',subject:[{name:app.name,digest:{sha256:d.subjects[2].digest.replace('sha256:','')}}],predicateType:'https://slsa.dev/verification_summary/v1',predicate:{verifier:{id:'cqp-poc'},timeVerified:d.evaluatedAt,resourceUri:`cqp://${app.id}/${d.decisionId}`,policy:{digest:d.policyDigest},verificationResult:d.outcome,_cqp:{rawOutcome:d.rawOutcome,mode:d.mode,reasons:d.rules,evidenceCompleteness:d.completeness}}};return{payloadType:'application/vnd.in-toto+json',payload:statement,signatures:[{keyid:'poc-ed25519-demo',sig:crypto.createHash('sha256').update(JSON.stringify(statement)).digest('base64'),demonstrationOnly:true}]};}
for(const app of applications)recordDecision(app,'initial_evaluation');

function json(res,status,value,headers={}){res.writeHead(status,{'Content-Type':'application/json; charset=utf-8','Cache-Control':'no-store',...headers});res.end(JSON.stringify(value));}
function readBody(req,done){let body='';req.on('data',c=>{body+=c;if(body.length>1e6)req.destroy();});req.on('end',()=>{try{done(null,JSON.parse(body||'{}'));}catch(e){done(e);}});}
function serveFile(reqPath,res){const relative=reqPath==='/'?'index.html':reqPath.slice(1),file=path.normalize(path.join(PUBLIC,relative));if(!file.startsWith(PUBLIC))return json(res,403,{error:'Forbidden'});fs.readFile(file,(error,data)=>{if(error)return json(res,404,{error:'Not found'});const type={'.html':'text/html','.css':'text/css','.js':'text/javascript','.svg':'image/svg+xml'}[path.extname(file)]||'application/octet-stream';res.writeHead(200,{'Content-Type':`${type}; charset=utf-8`});res.end(data);});}
const server=http.createServer((req,res)=>{const url=new URL(req.url,`http://${req.headers.host||'localhost'}`);if(req.method==='GET'&&url.pathname==='/api/apps')return json(res,200,applications.map(evaluate));if(req.method==='POST'&&url.pathname==='/api/reset')return json(res,200,{message:'In-memory demo state reset',apps:resetMemory()});const appMatch=url.pathname.match(/^\/api\/apps\/([^/]+)$/),actionMatch=url.pathname.match(/^\/api\/apps\/([^/]+)\/action$/),attestMatch=url.pathname.match(/^\/api\/apps\/([^/]+)\/attestation$/);if(req.method==='GET'&&appMatch){const app=applications.find(a=>a.id===appMatch[1]);return app?json(res,200,evaluate(app)):json(res,404,{error:'Application not found'});}if(req.method==='POST'&&actionMatch){const app=applications.find(a=>a.id===actionMatch[1]);if(!app)return json(res,404,{error:'Application not found'});return readBody(req,(error,body)=>{if(error)return json(res,400,{error:'Invalid JSON'});try{return json(res,200,applyAction(app,body));}catch(e){return json(res,400,{error:e.message});}});}if(req.method==='GET'&&attestMatch){const app=applications.find(a=>a.id===attestMatch[1]);if(!app)return json(res,404,{error:'Application not found'});return json(res,200,attestation(app),{'Content-Disposition':`attachment; filename="${app.id}-attestation.json"`});}if(req.method==='GET')return serveFile(url.pathname,res);json(res,405,{error:'Method not allowed'});});
if(require.main===module)server.listen(PORT,HOST,()=>console.log(`CQP POC running at http://${HOST}:${PORT}`));
module.exports={applications,evaluate,normalize,applyAction,attestation,resetMemory,runtime,server};
